"""Remove redundant unique constraint on workspace_id and content_hash

Revision ID: 6a3bc9ddb157
Revises: ae1dfed0ea4f
Create Date: 2025-11-29 13:26:48.592092

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6a3bc9ddb157"
down_revision: Union[str, Sequence[str], None] = "ae1dfed0ea4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_workspace_content_hash"), "documents", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_workspace_content_hash"), "documents", ["workspace_id", "content_hash"]
    )
    # ### end Alembic commands ###
