"""Pydantic schemas for RAG agent strategy generation.

This module defines the structured output models used by the LLM to generate
search strategies for decomposed queries.
"""

from pydantic import BaseModel


class Search(BaseModel):
    """A single search term with reasoning.

    Attributes:
        term: The search term/query to execute against the vector store
        reasoning: Explanation of why this search term was chosen
    """

    term: str
    reasoning: str


class SearchStrategy(BaseModel):
    """Strategy for searching documents based on user query.

    Generated by the LLM to decompose complex queries into multiple
    targeted searches for comprehensive retrieval.

    Attributes:
        reasoning: Overall reasoning for the search strategy
        searches: List of 1-5 search terms to execute in parallel
    """

    reasoning: str
    searches: list[Search]
